#!/bin/sh

set -e

SRC_DIR="$1"

working_tree_status=$(git status --porcelain)

for file in $(find ${SRC_DIR} -type f -name '*.h' -a \! -name 'tests.h')
do
	mkdir -p $(dirname api_h.tmp/$file)
	grep -Ev '^(#include <|class\s+\w+;)' $file > api_h.tmp/$file
done

cp src/protoapi.h api_h.tmp/src/

commit=$(git rev-parse --short HEAD)

printf "// This file is automatically generated from multiple header files.\n" > api_h.tmp/mdjpeg.h
printf "// It is provided in compact form for convenience, not for editing.\n" >> api_h.tmp/mdjpeg.h
printf "// Based on commit: ${commit}" >> api_h.tmp/mdjpeg.h
[ -n "$working_tree_status" ] && echo "-dirty" >> api_h.tmp/mdjpeg.h

printf "\n\n#pragma once\n\n" >> api_h.tmp/mdjpeg.h

find src -type f -name '*.h' -a \! -name 'tests.h' -exec grep -E '^#include <' '{}' \; | sort --unique >> api_h.tmp/mdjpeg.h
printf "\n\n" >> api_h.tmp/mdjpeg.h
find src -type f -name '*.h' -a \! -name 'tests.h' -exec grep -E '^class\s+\w+;' '{}' \; | sort --unique >> api_h.tmp/mdjpeg.h

g++ -E -P -C -nostdinc api_h.tmp/src/protoapi.h >> api_h.tmp/mdjpeg.h

mv api_h.tmp/mdjpeg.h obj/library
rm -rf api_h.tmp
